# Generated by Django 4.1.7 on 2023-02-23 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Album', 'Album'), ('EP', 'EP'), ('Single', 'Single')], max_length=50)),
                ('artwork', models.ImageField(blank=True, upload_to='', verbose_name='Album Artwork')),
                ('duration', models.DurationField(default=0)),
                ('released', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Artist Image')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DurationField(default=0)),
                ('released', models.DateField(blank=True)),
                ('album', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='songs', to='music.album')),
                ('artists', models.ManyToManyField(blank=True, related_name='songs', to='music.artist', verbose_name='Artist(s)')),
                ('features', models.ManyToManyField(blank=True, related_name='featured_on', to='music.artist', verbose_name='Feature(s)')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artwork', models.ImageField(upload_to='', verbose_name='Playlist Artwork')),
                ('duration', models.DurationField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Edited')),
                ('songs', models.ManyToManyField(blank=True, related_name='on_playlists', to='music.song')),
            ],
        ),
    ]
