# Generated by Django 4.1.7 on 2023-02-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created_by',
            field=models.JSONField(blank=True, default=dict, verbose_name='Created By'),
        ),
    ]
